const StyleDictionary = require('style-dictionary').default;

// Custom format: outputs TypeScript matching the existing hand-written
// src/tokens/colors.ts style (grouped consts with `as const`), instead of
// Style Dictionary's default flat JS output.
StyleDictionary.registerFormat({
  name: 'typescript/design-tokens',
  format: ({ dictionary }) => {
    const byCategory = {};

    for (const token of dictionary.allTokens) {
      // token.path looks like ["color", "primary"] or ["spacing", "xs"]
      const [category, ...rest] = token.path;
      const key = rest.join('-').replace(/-([a-z])/g, (_, c) => c.toUpperCase());
      if (!byCategory[category]) byCategory[category] = {};
      byCategory[category][key] = token.value;
    }

    let out = `// AUTO-GENERATED by Style Dictionary from tokens.json — do not hand-edit.
// Source of truth: src/tokens/tokens.json (synced from Figma via Tokens Studio)
// Regenerate with: npm run build:tokens

`;

    if (byCategory.color) {
      out += `export const colors = {\n`;
      for (const [k, v] of Object.entries(byCategory.color)) {
        out += `  ${k}: '${v}',\n`;
      }
      out += `} as const;\n\n`;
    }

    if (byCategory.spacing) {
      out += `export const spacing = {\n`;
      for (const [k, v] of Object.entries(byCategory.spacing)) {
        out += `  ${k}: '${v}px',\n`;
      }
      out += `} as const;\n\n`;
    }

    const hasTypography = byCategory.fontSize || byCategory.fontWeights || byCategory.fontFamilies;
    if (hasTypography) {
      out += `export const typography = {\n`;
      if (byCategory.fontFamilies?.body) {
        out += `  fontFamily: \`'${byCategory.fontFamilies.body}', -apple-system, sans-serif\`,\n`;
      }
      if (byCategory.fontSize) {
        out += `  sizes: {\n`;
        for (const [k, v] of Object.entries(byCategory.fontSize)) {
          out += `    ${k}: '${v}px',\n`;
        }
        out += `  },\n`;
      }
      if (byCategory.fontWeights) {
        out += `  weights: {\n`;
        for (const [k, v] of Object.entries(byCategory.fontWeights)) {
          out += `    ${k}: ${v},\n`;
        }
        out += `  },\n`;
      }
      out += `} as const;\n\n`;
    }

    if (byCategory.borderRadius) {
      out += `export const radii = {\n`;
      for (const [k, v] of Object.entries(byCategory.borderRadius)) {
        const val = v === '9999' ? '9999px' : `${v}px`;
        out += `  ${k}: '${val}',\n`;
      }
      out += `} as const;\n`;
    }

    return out;
  },
});

module.exports = {
  source: ['src/tokens/tokens.json'],
  platforms: {
    typescript: {
      transformGroup: 'js',
      buildPath: 'src/tokens/',
      files: [
        {
          destination: 'colors.ts',
          format: 'typescript/design-tokens',
        },
      ],
    },
  },
};