import StyleDictionary from 'style-dictionary';
import { register } from '@tokens-studio/sd-transforms';

register(StyleDictionary, { excludeParentKeys: true });

function groupTokensByCategory(dictionary) {
  const byCategory = {};

  for (const token of dictionary.allTokens) {
    let path = token.path;
    if (path[0] === 'global') path = path.slice(1);
    if (path[0] === 'comp') continue;

    const [category, ...rest] = path;
    const key = rest.join('-').replace(/-([a-z])/g, (_, c) => c.toUpperCase());
    if (!byCategory[category]) byCategory[category] = {};
    byCategory[category][key] = token.value;
  }

  return byCategory;
}

function getCompTokens(dictionary) {
  return dictionary.allTokens.filter((token) => token.path[0] === 'comp');
}

function toKebab(key) {
  return key.replace(/([A-Z])/g, '-$1').toLowerCase();
}

function withPx(value) {
  return typeof value === 'string' && value.endsWith('px') ? value : `${value}px`;
}

const generatedBanner = `// AUTO-GENERATED by Style Dictionary from tokens.json — do not hand-edit.
// Source of truth: src/tokens/tokens.json (synced from Figma via Tokens Studio)
// Regenerate with: npm run build:tokens
`;

const generatedCssBanner = `/* AUTO-GENERATED by Style Dictionary from tokens.json — do not hand-edit.
   Source of truth: src/tokens/tokens.json (synced from Figma via Tokens Studio)
   Regenerate with: npm run build:tokens */`;

StyleDictionary.registerFormat({
  name: 'typescript/design-tokens',
  format: ({ dictionary }) => {
    const byCategory = groupTokensByCategory(dictionary);

    let out = `${generatedBanner}\n`;

    if (byCategory.color) {
      out += `export const colors = {\n`;
      for (const [k, v] of Object.entries(byCategory.color)) {
        out += `  ${k}: '${v}',\n`;
      }
      out += `} as const;\n\n`;
    }

    if (byCategory.spacing) {
      out += `export const spacing = {\n`;
      for (const [k, v] of Object.entries(byCategory.spacing)) {
        out += `  ${k}: '${withPx(v)}',\n`;
      }
      out += `} as const;\n\n`;
    }

    const hasTypography = byCategory.fontSize || byCategory.fontWeights || byCategory.fontFamilies;
    if (hasTypography) {
      out += `export const typography = {\n`;
      if (byCategory.fontFamilies?.body) {
        out += `  fontFamily: \`'${byCategory.fontFamilies.body}', -apple-system, sans-serif\`,\n`;
      }
      if (byCategory.fontSize) {
        out += `  sizes: {\n`;
        for (const [k, v] of Object.entries(byCategory.fontSize)) {
          out += `    ${k}: '${withPx(v)}',\n`;
        }
        out += `  },\n`;
      }
      if (byCategory.fontWeights) {
        out += `  weights: {\n`;
        for (const [k, v] of Object.entries(byCategory.fontWeights)) {
          out += `    ${k}: ${v},\n`;
        }
        out += `  },\n`;
      }
      out += `} as const;\n\n`;
    }

    if (byCategory.borderRadius) {
      out += `export const radii = {\n`;
      for (const [k, v] of Object.entries(byCategory.borderRadius)) {
        const val = v === '9999' || v === '9999px' ? '9999px' : withPx(v);
        out += `  ${k}: '${val}',\n`;
      }
      out += `} as const;\n`;
    }

    return out;
  },
});

StyleDictionary.registerFormat({
  name: 'css/ds-variables',
  format: ({ dictionary }) => {
    const byCategory = groupTokensByCategory(dictionary);
    const compTokens = getCompTokens(dictionary);

    let out = `${generatedCssBanner}\n\n:root {\n`;

    if (byCategory.color) {
      for (const [k, v] of Object.entries(byCategory.color)) {
        out += `  --ds-color-${toKebab(k)}: ${v};\n`;
      }
    }

    if (byCategory.spacing) {
      for (const [k, v] of Object.entries(byCategory.spacing)) {
        out += `  --ds-spacing-${toKebab(k)}: ${withPx(v)};\n`;
      }
    }

    if (byCategory.fontFamilies?.body) {
      out += `  --ds-font-family: '${byCategory.fontFamilies.body}', -apple-system, sans-serif;\n`;
    }

    if (byCategory.fontSize) {
      for (const [k, v] of Object.entries(byCategory.fontSize)) {
        out += `  --ds-font-size-${toKebab(k)}: ${withPx(v)};\n`;
      }
    }

    if (byCategory.fontWeights) {
      for (const [k, v] of Object.entries(byCategory.fontWeights)) {
        out += `  --ds-font-weight-${toKebab(k)}: ${v};\n`;
      }
    }

    if (byCategory.borderRadius) {
      for (const [k, v] of Object.entries(byCategory.borderRadius)) {
        const val = v === '9999' || v === '9999px' ? '9999px' : withPx(v);
        out += `  --ds-radius-${toKebab(k)}: ${val};\n`;
      }
    }

    for (const token of compTokens) {
      out += `  --ds-${token.path.join('-')}: ${token.value};\n`;
    }

    out += `}\n`;
    return out;
  },
});

export default {
  source: ['src/tokens/tokens.json'],
  preprocessors: ['tokens-studio'],
  platforms: {
    typescript: {
      transformGroup: 'tokens-studio',
      buildPath: 'src/tokens/',
      files: [
        {
          destination: 'colors.ts',
          format: 'typescript/design-tokens',
        },
      ],
    },
    css: {
      transformGroup: 'tokens-studio',
      buildPath: 'src/tokens/',
      files: [
        {
          destination: 'variables.css',
          format: 'css/ds-variables',
        },
      ],
    },
  },
};
