import { readFileSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';
import StyleDictionary from 'style-dictionary';
import { register } from '@tokens-studio/sd-transforms';

register(StyleDictionary, { excludeParentKeys: true });

const __dirname = dirname(fileURLToPath(import.meta.url));
const TOKENS_PATH = join(__dirname, 'src/tokens/tokens.json');
const NORMALIZED_PATH = join(__dirname, 'src/tokens/.tokens.normalized.json');

const RESERVED_KEYS = new Set(['$themes', '$metadata']);

/**
 * Tokens Studio can push a duplicate set-name group inside a token set
 * (e.g. "comp/button": { "comp/button": { "comp": { "button": ... } } }).
 * That produces invalid CSS vars with slashes. Hoist children when detected.
 */
function unwrapDuplicateSetKeys(setContent, setName) {
  if (!setContent || typeof setContent !== 'object' || Array.isArray(setContent)) {
    return setContent;
  }

  if (Object.prototype.hasOwnProperty.call(setContent, setName)) {
    return unwrapDuplicateSetKeys(setContent[setName], setName);
  }

  const unwrapped = {};
  for (const [key, value] of Object.entries(setContent)) {
    unwrapped[key] =
      value && typeof value === 'object' && !Array.isArray(value)
        ? unwrapDuplicateSetKeys(value, setName)
        : value;
  }
  return unwrapped;
}

function syncMetadata(tokens) {
  const actualSets = Object.keys(tokens).filter((key) => !RESERVED_KEYS.has(key));
  const declaredOrder = tokens.$metadata?.tokenSetOrder ?? [];

  const ghostSets = declaredOrder.filter((setName) => !actualSets.includes(setName));
  const undeclaredSets = actualSets.filter((setName) => !declaredOrder.includes(setName));

  if (ghostSets.length > 0) {
    console.warn(
      `[tokens] $metadata.tokenSetOrder lists sets missing from tokens.json — delete these in Tokens Studio: ${ghostSets.join(', ')}`,
    );
  }

  if (undeclaredSets.length > 0) {
    console.warn(
      `[tokens] Token sets exist but are missing from $metadata.tokenSetOrder — drag to reorder in Tokens Studio: ${undeclaredSets.join(', ')}`,
    );
  }

  const reconciledOrder = [
    ...(actualSets.includes('global') ? ['global'] : []),
    ...declaredOrder.filter((setName) => setName !== 'global' && actualSets.includes(setName)),
    ...undeclaredSets,
  ];

  return {
    ...tokens.$metadata,
    tokenSetOrder: reconciledOrder.length > 0 ? reconciledOrder : actualSets,
  };
}

function normalizeTokenSets(tokens) {
  const normalized = { ...tokens };

  for (const [setName, setContent] of Object.entries(tokens)) {
    if (RESERVED_KEYS.has(setName)) continue;
    normalized[setName] = unwrapDuplicateSetKeys(setContent, setName);
  }

  normalized.$metadata = syncMetadata(normalized);

  return normalized;
}

const tokens = normalizeTokenSets(JSON.parse(readFileSync(TOKENS_PATH, 'utf8')));
writeFileSync(NORMALIZED_PATH, JSON.stringify(tokens, null, 2));

function parseKey(key) {
  return key.replace(/^\{|\}$/g, '').split('.');
}

function withPx(value) {
  if (typeof value !== 'string') return `${value}px`;
  if (
    value.endsWith('px') ||
    value.endsWith('em') ||
    value.includes('rgba') ||
    value.startsWith('#') ||
    value === 'transparent'
  ) {
    return value;
  }
  return `${value}px`;
}

function tokenKeyToCssVar(key) {
  return `--ds-${key}`;
}

function groupTokensByKey(dictionary) {
  const global = {};
  const comp = {};

  for (const token of dictionary.allTokens) {
    const parts = parseKey(token.key);
    const bucket = parts[0] === 'comp' ? comp : global;
    const flatKey = parts.join('-');
    bucket[flatKey] = { value: token.value, type: token.type, parts };
  }

  return { global, comp };
}

const generatedCssBanner = `/* AUTO-GENERATED by Style Dictionary from tokens.json — do not hand-edit.
   Source of truth: src/tokens/tokens.json (synced from Figma via Tokens Studio)
   Regenerate with: npm run build:tokens */`;

StyleDictionary.registerFormat({
  name: 'css/ds-variables',
  format: ({ dictionary }) => {
    const { global, comp } = groupTokensByKey(dictionary);

    let out = `${generatedCssBanner}\n\n:root {\n`;

    for (const [key, { value, type }] of Object.entries(global)) {
      const varName = tokenKeyToCssVar(key);
      if (type === 'fontSizes' || type === 'spacing' || type === 'borderRadius') {
        out += `  ${varName}: ${withPx(value)};\n`;
      } else if (type === 'fontFamilies') {
        const role = key.replace('fontFamilies-', '');
        const fallback = role === 'mono' ? 'monospace' : 'sans-serif';
        out += `  ${varName}: '${value}', ${fallback};\n`;
      } else {
        out += `  ${varName}: ${value};\n`;
      }
    }

    out += `  --ds-font-family: var(--ds-fontFamilies-body);\n`;
    out += `  --ds-font-display: var(--ds-fontFamilies-display);\n`;
    out += `  --ds-font-body: var(--ds-fontFamilies-body);\n`;
    out += `  --ds-font-mono: var(--ds-fontFamilies-mono);\n`;

    for (const [key, { value, type }] of Object.entries(comp)) {
      const varName = tokenKeyToCssVar(key);
      const val =
        type === 'fontSizes' || type === 'spacing' || type === 'borderRadius'
          ? withPx(value)
          : value;
      out += `  ${varName}: ${val};\n`;
    }

    out += `}\n`;
    return out;
  },
});

export default {
  source: [NORMALIZED_PATH],
  preprocessors: ['tokens-studio'],
  platforms: {
    css: {
      transformGroup: 'tokens-studio',
      buildPath: 'dist/',
      files: [{ destination: 'variables.css', format: 'css/ds-variables' }],
    },
  },
};
