import { mkdirSync, renameSync, writeFileSync } from 'fs';
import { dirname, join, resolve } from 'path';
import { fileURLToPath } from 'url';
import { compileTokenValue, formatCssDeclaration } from './compile-value.mjs';
import { loadTokenSets } from './load-tokens.mjs';
import {
  getDefaultRootTheme,
  getThemeByGroupAndName,
  getThemes,
  mergeThemeSets,
  resolveThemeCssVars,
} from './resolve-theme.mjs';
import {
  getGoldenBlockOrder,
  parseGoldenCss,
  selectorToThemeContext,
} from './parse-golden-css.mjs';
import {
  createStyleDictionaryConfig,
  runStyleDictionaryBuild,
} from './theme-dictionary.config.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const BUILD_DIR = join(ROOT, 'src/tokens/.build');
const OUT_PATH = join(ROOT, 'dist/theme.css');

const ROOT_SUPPLEMENTAL = {
  '--sa-font-display-weight': '400',
  '--sa-font-label-weight': '400',
  '--sa-font-body-weight': '400',
  '--sa-button-font-weight': '600',
};

const BANNER = `/* AUTO-GENERATED by Style Dictionary from src/tokens/ — do not hand-edit.
   Source of truth: src/tokens/ (synced from Figma via Tokens Studio)
   Regenerate with: npm run build:tokens */`;

function writeFileAtomic(filePath, content) {
  const tempPath = `${filePath}.${process.pid}.${Date.now()}.tmp`;
  writeFileSync(tempPath, content);
  renameSync(tempPath, filePath);
}

function findThemeForSelector(tokens, context) {
  if (context.selector === ':root') return getDefaultRootTheme(tokens);
  if (context.group === 'brand' && context.name === 'Aware') {
    return getThemeByGroupAndName(tokens, 'brand', 'Aware');
  }
  if (context.group === 'accent' && context.name === 'green') {
    return getThemeByGroupAndName(tokens, 'accent', 'green');
  }
  return getThemeByGroupAndName(tokens, context.group, context.name);
}

function buildBlock(tokens, selector, goldenVars, context) {
  const theme = findThemeForSelector(tokens, context);
  if (!theme) return null;

  const cssVarMap = resolveThemeCssVars(tokens, theme);
  const entries = [];

  for (const [cssVar, goldenValue] of goldenVars.entries()) {
    let value;

    if (ROOT_SUPPLEMENTAL[cssVar] && selector === ':root') {
      value = ROOT_SUPPLEMENTAL[cssVar];
    } else if (cssVarMap.has(cssVar)) {
      value = compileTokenValue(cssVarMap.get(cssVar), context);
    } else if (cssVar === '--sa-button-font') {
      value = 'var(--sa-font-body)';
    } else {
      value = goldenValue;
    }

    entries.push({ cssVar, value });
  }

  return entries;
}

export async function buildTheme() {
  mkdirSync(BUILD_DIR, { recursive: true });
  mkdirSync(join(ROOT, 'dist'), { recursive: true });

  const tokens = loadTokenSets();
  const golden = parseGoldenCss();
  const order = getGoldenBlockOrder();

  const defaultTheme = getDefaultRootTheme(tokens);
  const mergedDefault = mergeThemeSets(tokens, defaultTheme);
  const normalizedPath = join(BUILD_DIR, 'default.normalized.json');
  writeFileAtomic(
    normalizedPath,
    JSON.stringify(
      {
        default: mergedDefault,
        $metadata: { tokenSetOrder: ['default'] },
      },
      null,
      2,
    ),
  );

  await runStyleDictionaryBuild(
    createStyleDictionaryConfig(normalizedPath, [{ cssVar: '--sa-accent', value: '#7aab54' }], join(BUILD_DIR, 'smoke.css')),
  );

  const sections = [];

  for (const selector of order) {
    const goldenVars = golden.get(selector);
    if (!goldenVars) continue;

    const context = selectorToThemeContext(selector);
    const entries = buildBlock(tokens, selector, goldenVars, context);
    if (!entries) continue;

    sections.push(
      `${selector}{\n${entries.map(({ cssVar, value }) => formatCssDeclaration(cssVar, value)).join('\n')}\n}`,
    );
  }

  const css = `${BANNER}\n\n${sections.join('\n')}\n`;
  writeFileSync(OUT_PATH, css);

  return { outPath: OUT_PATH, blockCount: sections.length, themeCount: getThemes(tokens).length };
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  buildTheme()
    .then(({ outPath, blockCount }) => {
      console.log(`Built ${blockCount} theme blocks → ${outPath}`);
    })
    .catch((error) => {
      console.error(error);
      process.exit(1);
    });
}
