// AUTO-GENERATED by Style Dictionary from tokens.json — do not hand-edit.
// Source of truth: src/tokens/tokens.json (synced from Figma via Tokens Studio)
// Regenerate with: npm run build:tokens

export const colors = {
  ink: '#191512',
  white: '#ffffff',
  surfacePrimary: '#fffdf9',
  surfaceSecondary: '#f7f3ec',
  surfaceTertiary: '#ece5d8',
  accentTeal: '#2f9b91',
  accentGold: '#d3a044',
  accentTerracotta: '#c25538',
  accentPurple: '#8668bd',
  accentGreen: '#7aab54',
  textPrimary: '#191512',
  textBody: 'rgba(25, 21, 18, 0.82)',
  textMuted: 'rgba(25, 21, 18, 0.65)',
  textSubtle: 'rgba(25, 21, 18, 0.5)',
  textOnDark: '#ffffff',
  textOnDarkMuted: 'rgba(255, 255, 255, 0.85)',
  textOnDarkSubtle: 'rgba(255, 255, 255, 0.6)',
  borderStrong: 'rgba(25, 21, 18, 0.35)',
  borderDefault: 'rgba(25, 21, 18, 0.25)',
  borderSubtle: 'rgba(25, 21, 18, 0.14)',
  overlayDark: 'rgba(0, 0, 0, 0.65)',
  overlayScrim: 'rgba(0, 0, 0, 0.55)',
} as const;

export const spacing = {
  xs: '4px',
  sm: '8px',
  md: '16px',
  lg: '24px',
  xl: '32px',
  2xl: '48px',
  3xl: '64px',
  4xl: '96px',
} as const;

export const typography = {
  fontFamily: `''Space Grotesk'', -apple-system, sans-serif`,
  sizes: {
    displayHero: '168px',
    displayXl: '118px',
    displayLg: '100px',
    displayMd: '72px',
    displaySm: '44px',
    bodyLg: '18px',
    bodyMd: '16px',
    bodySm: '13px',
    bodyCaption: '12px',
    monoMd: '12px',
    monoSm: '11px',
    monoXs: '9px',
  },
  weights: {
    regular: 400,
    medium: 500,
    bold: 700,
  },
} as const;

export const radii = {
  pill: '28px',
  pillSm: '16px',
  input: '14px',
  overlay: '6px',
  card: '12px',
} as const;
