// AUTO-GENERATED by Style Dictionary from tokens.json — do not hand-edit.
// Source of truth: src/tokens/tokens.json (synced from Figma via Tokens Studio)
// Regenerate with: npm run build:tokens

export const colors = {
  primary: '#47c4e6',
  primaryOn: '#ffffff',
  primaryHover: '#07363b',
  secondary: '#f3f4f6',
  secondaryHover: '#e5e7eb',
  text: '#111827',
  textMuted: '#6b7280',
  border: '#d1d5db',
  danger: '#dc2626',
  background: '#ffffff',
} as const;

export const spacing = {
  xs: '4px',
  sm: '8px',
  md: '16px',
  lg: '24px',
  xl: '32px',
} as const;

export const typography = {
  fontFamily: `'Inter', -apple-system, sans-serif`,
  sizes: {
    sm: '14px',
    md: '16px',
    lg: '20px',
    xl: '28px',
  },
  weights: {
    regular: 400,
    medium: 500,
    bold: 700,
  },
} as const;

export const radii = {
  sm: '4px',
  md: '8px',
  lg: '12px',
  full: '9999px',
} as const;
