// AUTO-GENERATED by Style Dictionary from tokens.json — do not hand-edit.
// Source of truth: src/tokens/tokens.json (synced from Figma via Tokens Studio)
// Regenerate with: npm run build:tokens

export const colors = {
  "ink": "#191512",
  "ink.hover": "#3a332b",
  "white": "#ffffff",
  "surface.primary": "#ffffff",
  "surface.secondary": "#f7f3ec",
  "surface.tertiary": "#ece5d8",
  "surface.hover": "#f2ecdf",
  "accent.pink": "#db0081",
  "accent.pink.deep": "#ad005f",
  "accent.teal": "#2f9b91",
  "accent.teal.deep": "#1c7069",
  "accent.gold": "#d3a044",
  "accent.gold.deep": "#a3762a",
  "accent.terracotta": "#c25538",
  "accent.terracotta.deep": "#96371e",
  "accent.purple": "#8668bd",
  "accent.purple.deep": "#5f4494",
  "accent.green": "#7aab54",
  "accent.green.deep": "#557f36",
  "text.primary": "#191512",
  "text.body": "rgba(25, 21, 18, 0.82)",
  "text.muted": "rgba(25, 21, 18, 0.65)",
  "text.subtle": "rgba(25, 21, 18, 0.50)",
  "text.on.dark": "#ffffff",
  "text.on.dark.muted": "rgba(255, 255, 255, 0.85)",
  "text.on.dark.subtle": "rgba(255, 255, 255, 0.60)",
  "text.accent": "#c25538",
  "border.strong": "rgba(25, 21, 18, 0.35)",
  "border.default": "rgba(25, 21, 18, 0.25)",
  "border.subtle": "rgba(25, 21, 18, 0.14)",
  "overlay.dark": "rgba(0, 0, 0, 0.65)",
  "overlay.scrim": "rgba(0, 0, 0, 0.55)"
} as const;

export const spacing = {
  "xs": "4px",
  "sm": "8px",
  "md": "16px",
  "lg": "24px",
  "xl": "32px",
  "2xl": "48px",
  "3xl": "64px",
  "4xl": "96px"
} as const;

export const fontFamilies = {
  "display": "'Space Grotesk'",
  "body": "'IBM Plex Mono'",
  "mono": "'Space Mono'",
  "space-grotesk": "'Space Grotesk'",
  "ibm-plex": "'IBM Plex Mono'"
} as const;

export const fontWeights = {
  "regular": null,
  "medium": null,
  "semibold": null,
  "bold": null
} as const;

export const fontSizes = {
  "display.hero": "168px",
  "display.xl": "118px",
  "display.lg": "100px",
  "display.md": "72px",
  "display.sm": "44px",
  "display.xs": "28px",
  "body.lg": "18px",
  "body.md": "16px",
  "body.sm": "13px",
  "body.caption": "12px",
  "mono.md": "12px",
  "mono.sm": "11px",
  "mono.xs": "9px"
} as const;

export const lineHeights = {
  "display": "0.9",
  "snug": "1",
  "heading": "1.1",
  "body": "1.4",
  "relaxed": "1.55"
} as const;

export const letterSpacing = {
  "display": "0.01em",
  "mono-wide": "0.12em",
  "mono-widest": "0.14em"
} as const;

export const radii = {
  "pill": "28px",
  "pill-sm": "16px",
  "input": "14px",
  "overlay": "6px",
  "card": "12px"
} as const;

export const typography = {
  fontFamily: {
    display: `''Space Grotesk'', sans-serif`,
    body: `''IBM Plex Mono'', sans-serif`,
    mono: `''Space Mono'', monospace`,
  },
  sizes: fontSizes,
  weights: fontWeights,
  lineHeights,
  letterSpacing,
} as const;
